#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));
const APP_ROOT_PATH = __DIR__;
const APP_ENV_PATH = APP_ROOT_PATH;

// Register the Composer autoloader...
require APP_ROOT_PATH .'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$status = (require_once APP_ROOT_PATH .'/bootstrap/app.php')
    ->handleCommand(new ArgvInput);

exit($status);
